### ISSUE TITLE
[BUG] After upgrading to latest versions of Agora plugin, videos no longer working

### ISSUE THREAD

**Issue by geotraveler** [AgoraIO/Agora-WordPress#129]
After upgrading to latest versions of Agora plugin, videos no longer working and it looks like there might be an issue with the layout as well. 

Here are screenshots of the error messages in the browser. None of the buttons work (clicking to Leave Meeting or Expand View, etc).

Here is the link you can check - [https://www.localpurse.com/pod/ikyoilfz/](https://www.localpurse.com/pod/ikyoilfz/)

Please advise as this is work stoppage, thanks!

![Error Agora 2](https://user-images.githubusercontent.com/74770503/195339721-4e397b62-a058-40f7-b028-c3531f8cb458.png)

**Comment by geotraveler** [comment]
Here is the main error message:

`agora-communication-client.js:45 Uncaught TypeError: window.AGORA_UTILS.agoraJoinChannel is not a function
    at agora-communication-client.js:45:24
    at callback (AgoraRTCSDK-3.6.11.js:14:63511)
    at AgoraRTCSDK-3.6.11.js:2:36697
    at t.init (AgoraRTCSDK-3.6.11.js:14:63772)
    at Object.initClientAndJoinChannel (agora-communication-client.js:43:15)
    at (index):1339:39`

**Comment by geotraveler** [comment]
Great to meet you @EkaanshArora! We're currently at work stoppage because the plugin is no longer working and throwing the error I shared above. Please advise as soon as you can.
Thanks

**Comment by EkaanshArora** [comment]
We're sorry about the issue you are facing - can you please open a support ticket at https://agora-ticket.agora.io/?

**Comment by geotraveler** [comment]
Hej Ekaansh,
I have created the support ticket.
Please advise.
Thanks,

Lola

*Your friends @ Local Purse*
________________________________
Find us: www.localpurse.com
Follow us: Twitter <https://www.twitter.com/LocalPurse> - Instagram
<https://www.instagram.com/MyLocalPurse> - Facebook
<https://www.facebook.com/LocalPurse>

**Comment by geotraveler** [comment]
@EkaanshArora -  As I mentioned, I've created the support ticket. Please, this is critical work stoppage for us. We have a livestream coming up very soon with registered viewers.
And our entire site is broken because it's dependent on the Agora Wordpress Plugin.
Please advise

**Comment by EkaanshArora** [comment]
I'm sorry you're facing this issue still. I tried installing the latest version of the plugin to a fresh new wordpress project and it works fine for me, I wasn't able to reproduce the bug you've described. I'd suggest trying an earlier version or doing a fresh install to see if that fixes the issue.
If you're still facing issues please share your support ticket number at [ekaansh@agora.io]() I will try and escalate.

**Comment by geotraveler** [comment]
Please escalate it -  CUS-27482
<http://agora-ticket.agora.io/issue/81719c241b8d438a8b7811a0384f3c42>
I have shared the error we're getting in the browser. I have also shared
the admin login so you can troubleshoot.
I've tried installing earlier versions and it didn't fix the issue. Are
there any known plugin conflicts?
Thanks,
Lola

*Your friends @ Local Purse*
________________________________
Find us: www.localpurse.com
Follow us: Twitter <https://www.twitter.com/LocalPurse> - Instagram
<https://www.instagram.com/MyLocalPurse> - Facebook
<https://www.facebook.com/LocalPurse>
